name: Build Tests

on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron: "0 4 * * 2"
  workflow_dispatch:

jobs:
  test:
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
    - name: Pull the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.7.0

    - name: Set up JDK 11
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.2.2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Verify with Maven
      run: mvn --batch-mode verify -Dmaven.javadoc.skip=true
