name: Build Tests

on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
    - name: Pull the repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Run tests
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 60
        max_attempts: 1
        command: mvn --batch-mode verify -Dmaven.javadoc.skip=true
        on_retry_command: mvn --batch-mode clean
